jobs:
  - job_type: hello
    id: 100
    name: Hello-DB
    connection_profile: unity_worker_db
    queries:
    - name: hello_truncate_canary
      action_type: execute_one
    - name: hello_select_count_canary
      action_type: select_one
    - name: hello_select_canary
      action_type: select_many
      pass_result_flag: true
    - name: hello_execute_many_canary
      action_type: execute_many
    - name: hello_select_count_abc_canary
      action_type: select_one  
      args:
        - 1001
    - name: hello_select_count_abc_def_canary
      action_type: select_one
      args:
        - 1001
        - 1002     
    startup: true
    delay: 600
    run_once: false
    run_next: [101]
  - job_type: hello
    id: 101
    name: Hello-Api
    connection_profile: unity_worker_api
    cmd: /info
  - job_type: hello
    id: 102
    name: Hello-Manual-Io
    action_type: subprocess
    connection_profile: unity_worker_io
    cmd: >-
      python -c "import json,datetime,uuid; print(json.dumps({'hello':'id-'+uuid.uuid4().hex[:8],'timestamp':datetime.datetime.now(datetime.timezone.utc).isoformat(timespec='seconds').replace('+00:00','Z')}))"
  - job_type: hello
    id: 103
    name: Hello-Manual-Io-Error
    action_type: subprocess
    connection_profile: unity_worker_io
    cmd: >-
      python -c "raise RuntimeError('Manual Error')"
  - job_type: admin
    id: 1004
    name: OpsLedger
    source_connection_profile: unity_worker_redis
    source_cmd: tbd
    target_connection_profile: unity_worker_db
    target_cmd: admin_bulk_insert
    startup: false
    run_once: True
    delay: 0
