FROM python:3.13-slim

WORKDIR /app

# Install Python packages
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY VERSION .
COPY deploy/sitecustomize.py ./sitecustomize.py
COPY . .

RUN touch /tmp/healthy

CMD ["fastapi", "run", "src/api/main.py", "--host", "0.0.0.0", "--port", "80"]